name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: 
      - completed

jobs:
  deployment:
    name: CD
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}  
